import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";

// import { Koh_Santepheap } from "next/font/google";
// const koh_Santepheap = Koh_Santepheap({ 
//   subsets: ["latin"],
//   weight: ["400", "700","900"],

// });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
